### ISSUE TITLE
Unity 2020.3.4 - URP 10.4.0 - Works in editor/dev build, but not in release build

### ISSUE THREAD

**Issue by MeatG** [yahiaetman/URPCustomPostProcessingStack#1]
I upgraded to Unity 2020.3 and URP 10.4.0
All effects work fine when playing in editor or in a development build, but effects are
disabled in the release build for some unknown reason. 

This is partly my mistake - I forgot to test in normal build and also forgot that this package works only in 2020.2

-Tested on MacOS Big Sur and Windows 10 - both have the same problem.
-No errors in player.log.

What could cause this? Would it be easy to fix?

**Comment by yahiaetman** [comment]
Do you use [Managed Stripping](https://docs.unity3d.com/Manual/ManagedCodeStripping.html)?
The code relies on reflection during the initialization step to create an instance of each effect renderer in the list.
There are no other reference to the effect renderers in the code that would protect them from being stripped out.

So if you have managed stripping enabled, could you either:
- Disable it and try?
- Use the [[Preserve](https://docs.unity3d.com/ScriptReference/Scripting.PreserveAttribute.html)] attribute on the effect renderers that you want to keep.

Could you try and see if this works?

**Comment by MeatG** [comment]
Hi,

Thanks for the quick answer! Managed stripping has been disabled all the time. Should I still try the Preserve attribute?
If so, where exactly should I apply it?

Could the depencies of the package(.json) affect this?

**Comment by MeatG** [comment]
And what would be the difference between development build and normal build in this regard?

**Comment by yahiaetman** [comment]
I think it is worth trying. I am currently trying it on Unity 2020.3.4 on my machine.
I believe Unity builds the project in debug mode for the development build.

**Comment by MeatG** [comment]
> I think it is worth trying. I am currently trying it on Unity 2020.3.4 on my machine.
> I believe Unity builds the project in debug mode for the development build.

FYI, I tried both 2020.3.4 and 2020.3.5 - both have the same problem

**Comment by yahiaetman** [comment]
Ok, the build finally finished.

I tried it without adding the [Preserve] attribute and it still worked fine for me.

I built it on Windows 10 for Window x86_64.
My Player Settings:
- Scripting Backend: IL2CPP.
- Api Compatibility Level: .Net 4.x
- C++ Compiler Configuration: Release.
- Use Incremental GC: No. (Edit: I don't think that this would matter)
- Managed stripping level: Low.

My Build Settings:
- Development Build: No.

Is your settings different? If yes, what is the difference?

**Comment by MeatG** [comment]
-I made a new project: **Works**
-Tried your settings in my project: **Not working**
-Made a completely new scene to my project with only one effect active: **Not working**

So there is something strange going on on my end... I have been chasing this bug in my code and settings for quite a long time before posting here. No idea what to do next :D

**Comment by yahiaetman** [comment]
Is it possible for you to send me the new project to try it on my machine?

**Comment by MeatG** [comment]
Got it!! 

I have a big project with many years of development so it is not always easy to find problems - BUT I finally did find it!
It was a code obfuscator asset I was using.

Thank you so much for your help, anyways. Give me your PayPal -address so I can buy you a beer. :)

**Comment by MeatG** [comment]
In the obfuscator, there was an option set to NOT obfuscate development version so that was the 'strange' thing
